"""Multi-Track Engineer for HIV-1 Protease parallel discovery.

Implements four parallel discovery tracks, each seeding from a different
data source to ensure structural diversity. Molecules appearing in multiple
tracks are flagged as convergence candidates.

Track A — ChEMBL Top Actives
    Seeds from the highest-activity ChEMBL bioassay records.
    Explores hydroxyethylamine (HEA) scaffold modifications.

Track B — PDB Co-Crystal Ligands
    Seeds from experimentally validated PDB co-crystal structures.
    Structure-guided modifications of P2/P2' groups.

Track C — BindingDB Curated
    Seeds from BindingDB curated HIV protease records.
    Explores bis-THF and carbamate variants.

Track D — Diverse Scaffolds
    Fragment-based and macrocyclic exploration.
    Targets novel scaffold families with low Tanimoto similarity to
    approved drugs. Uses guided bit-flip mutation from the cognition store.
"""
from __future__ import annotations

import logging
import math
import warnings
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem, DataStructs, rdMolDescriptors
        from rdkit.Chem import rdFingerprintGenerator
        RDKIT_AVAILABLE = True
    except ImportError:
        RDKIT_AVAILABLE = False

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Track definitions
# ---------------------------------------------------------------------------

TRACK_A = "A"  # ChEMBL Top Actives — HEA scaffold
TRACK_B = "B"  # PDB Co-Crystal Ligands
TRACK_C = "C"  # BindingDB Curated — bis-THF / carbamate
TRACK_D = "D"  # Diverse Scaffolds — guided mutation

# Approved HIV PI SMILES as track seeds (from PDB co-crystal structures)
TRACK_SEEDS: Dict[str, List[str]] = {
    TRACK_A: [
        # Darunavir — HEA scaffold, highest clinical potency
        "O=C(N[C@@H](Cc1ccccc1)[C@@H](O)C[C@@H](Cc1ccccc1)NC(=O)OC1COC2CCOC12)c1ccc(N)cc1",
        # Amprenavir — HEA scaffold
        "CC(C)CN1C(=O)[C@@H](Cc2ccccc2)NC(=O)[C@@H]1CC(=O)NS(=O)(=O)c1ccc(N)cc1",
        # Lopinavir — HEA scaffold
        "CC1=C(C(=O)N[C@@H](CC(C)C)C(=O)N2CC[C@H](O)[C@@H]2Cc2ccccc2)N=C(N)N1",
    ],
    TRACK_B: [
        # Indinavir — PDB 1HSG
        "OC(CN1CC2CCCC2CC1Cc1cccnc1)C(=O)NC(Cc1ccccc1)C(=O)NC(CC(C)C)C(=O)O",
        # Nelfinavir — PDB 1OHR
        "CC1=C(C(=O)NC(CSc2ccccc2)C(=O)N[C@@H](Cc2ccccc2)[C@@H](O)CN2CC3CCCC3CC2)N=C(N)N1",
        # Atazanavir — PDB 2AQU
        "COC(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@H](C[C@@H](O)[C@H](Cc1ccccc1)NC(=O)[C@@H](NC(=O)OC)Cc1ccccc1)Cc1ccc(cc1)-c1ccccc1",
    ],
    TRACK_C: [
        # Bis-THF scaffold — BindingDB curated
        "O=C(N[C@@H](Cc1ccccc1)[C@@H](O)C[C@@H](Cc1ccccc1)NC(=O)OC1COC2CCOC12)c1ccc(N)cc1",
        # Carbamate variant
        "CC(C)OC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@@H](Cc1ccccc1)NC(=O)c1ccc(N)cc1",
        # Tipranavir fragment
        "O=C(NC(Cc1ccccc1)C(=O)NC(CC(C)C)C(=O)O)c1cc(F)ccc1F",
    ],
    TRACK_D: [
        # Fragment — benzimidazole scaffold
        "c1ccc2[nH]cnc2c1",
        # Macrocycle seed
        "O=C1CCCCCCC(=O)N[C@@H](Cc2ccccc2)C(=O)N[C@@H](CC(C)C)C1",
        # Spiro scaffold
        "O=C1NC2(CCCC2)C(=O)N1Cc1ccccc1",
    ],
}

# Approved HIV PI InChI keys for novelty check
APPROVED_PI_INCHI_KEYS = {
    "CJBJHOAVZSMMDJ-UPHRSURJSA-N",  # Darunavir
    "AXRYRYVKAWYZBR-GASJEMHNSA-N",  # Atazanavir
    "KJHKTHWMRKYKJE-SUGCFTRWSA-N",  # Indinavir
    "NQDJXKOVJZTUJA-MHZLTWQESA-N",  # Lopinavir
    "HBOMLICNUCNMMY-XLPZGREQSA-N",  # Nelfinavir
    "SUJUHGSWHZTSEU-FYBSXWGRSA-N",  # Ritonavir
    "BHMBVRSPMRZVAB-CUYCHFNGSA-N",  # Saquinavir
    "NCDNCNXCDXHOMX-XGKFQTISBSA-N", # Tipranavir
    "YMARZQAQMVYCKC-RVBZMBCESA-N",  # Fosamprenavir
    "JTEGQNKMBCTBCH-UUOKFMHZSA-N",  # Amprenavir
}


@dataclass
class TrackCandidate:
    """A molecular candidate generated by a specific track."""
    smiles: str
    track: str
    parent_smiles: str
    modification_type: str
    predicted_pic50: Optional[float] = None
    confidence: float = 0.0
    fingerprint: Optional[np.ndarray] = None
    is_novel: bool = True
    tanimoto_to_approved: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


class MultiTrackEngineer:
    """Parallel 4-track molecular engineer for HIV-1 Protease discovery.

    Each track generates candidates from a different seed source.
    The engineer maintains per-track state and supports convergence
    detection across tracks.

    Parameters
    ----------
    fingerprint_radius:
        Morgan fingerprint radius (default 2 = ECFP4).
    fingerprint_nbits:
        Fingerprint bit vector length (default 2048).
    novelty_tanimoto_threshold:
        Maximum Tanimoto similarity to approved drugs for a candidate
        to be considered novel (default 0.85).
    """

    def __init__(
        self,
        fingerprint_radius: int = 2,
        fingerprint_nbits: int = 2048,
        novelty_tanimoto_threshold: float = 0.85,
    ) -> None:
        self.radius = fingerprint_radius
        self.nbits = fingerprint_nbits
        self.novelty_threshold = novelty_tanimoto_threshold

        # Per-track candidate history for convergence detection
        self._track_candidates: Dict[str, List[TrackCandidate]] = {
            TRACK_A: [], TRACK_B: [], TRACK_C: [], TRACK_D: [],
        }

        # Pre-compute approved PI fingerprints for novelty check
        self._approved_fps: List[Any] = []
        if RDKIT_AVAILABLE:
            gen = rdFingerprintGenerator.GetMorganGenerator(
                radius=self.radius, fpSize=self.nbits
            )
            for smiles in [
                "O=C(N[C@@H](Cc1ccccc1)[C@@H](O)C[C@@H](Cc1ccccc1)NC(=O)OC1COC2CCOC12)c1ccc(N)cc1",
                "CC(C)CN1C(=O)[C@@H](Cc2ccccc2)NC(=O)[C@@H]1CC(=O)NS(=O)(=O)c1ccc(N)cc1",
                "OC(CN1CC2CCCC2CC1Cc1cccnc1)C(=O)NC(Cc1ccccc1)C(=O)NC(CC(C)C)C(=O)O",
            ]:
                mol = Chem.MolFromSmiles(smiles)
                if mol:
                    self._approved_fps.append(gen.GetFingerprint(mol))

        logger.info(
            "MultiTrackEngineer initialized: radius=%d, nbits=%d, %d approved PIs loaded",
            self.radius, self.nbits, len(self._approved_fps),
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_track(
        self,
        track: str,
        n_candidates: int = 50,
        cognition_patterns: Optional[Dict[str, Any]] = None,
    ) -> List[TrackCandidate]:
        """Generate candidates for a single track.

        Parameters
        ----------
        track:
            One of TRACK_A, TRACK_B, TRACK_C, TRACK_D.
        n_candidates:
            Number of candidates to generate.
        cognition_patterns:
            Per-bit statistics from the CognitionStore (used by Track D
            for guided mutation).

        Returns
        -------
        List[TrackCandidate]
            Generated candidates with fingerprints and novelty scores.
        """
        if not RDKIT_AVAILABLE:
            logger.warning("RDKit not available — returning empty track %s", track)
            return []

        seeds = TRACK_SEEDS.get(track, [])
        if not seeds:
            logger.warning("No seeds for track %s", track)
            return []

        candidates: List[TrackCandidate] = []
        # Use ceiling division so that n_candidates=5 with 3 seeds gives
        # ceil(5/3)=2 per seed → 6 total, then slice to exactly n_candidates.
        per_seed = max(1, math.ceil(n_candidates / len(seeds)))

        for seed_smiles in seeds:
            seed_mol = Chem.MolFromSmiles(seed_smiles)
            if seed_mol is None:
                continue

            if track == TRACK_D and cognition_patterns:
                new_candidates = self._guided_mutation(
                    seed_mol, seed_smiles, per_seed, cognition_patterns, track
                )
            elif track == TRACK_A:
                new_candidates = self._hea_scaffold_modification(
                    seed_mol, seed_smiles, per_seed, track
                )
            elif track == TRACK_B:
                new_candidates = self._p2_group_modification(
                    seed_mol, seed_smiles, per_seed, track
                )
            elif track == TRACK_C:
                new_candidates = self._bis_thf_modification(
                    seed_mol, seed_smiles, per_seed, track
                )
            else:
                new_candidates = self._random_modification(
                    seed_mol, seed_smiles, per_seed, track
                )

            candidates.extend(new_candidates)

        # Compute fingerprints and novelty scores
        gen = rdFingerprintGenerator.GetMorganGenerator(
            radius=self.radius, fpSize=self.nbits
        )
        for cand in candidates:
            mol = Chem.MolFromSmiles(cand.smiles)
            if mol:
                fp = gen.GetFingerprint(mol)
                cand.fingerprint = np.array(fp)
                cand.tanimoto_to_approved = self._max_tanimoto_to_approved(fp)
                cand.is_novel = cand.tanimoto_to_approved < self.novelty_threshold

        # Trim to exactly n_candidates (ceiling division may overshoot)
        candidates = candidates[:n_candidates]

        # Store for convergence detection
        self._track_candidates[track].extend(candidates)

        logger.info(
            "Track %s: generated %d candidates (%d novel)",
            track, len(candidates), sum(1 for c in candidates if c.is_novel),
        )
        return candidates

    def generate_all_tracks(
        self,
        n_per_track: int = 50,
        cognition_patterns: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, List[TrackCandidate]]:
        """Generate candidates for all four tracks in parallel.

        Parameters
        ----------
        n_per_track:
            Number of candidates per track.
        cognition_patterns:
            Per-bit statistics from the CognitionStore for Track D.

        Returns
        -------
        Dict mapping track name to list of candidates.
        """
        results: Dict[str, List[TrackCandidate]] = {}
        for track in [TRACK_A, TRACK_B, TRACK_C, TRACK_D]:
            results[track] = self.generate_track(
                track, n_per_track, cognition_patterns
            )
        total = sum(len(v) for v in results.values())
        logger.info("All tracks generated: %d total candidates", total)
        return results

    def find_convergence_candidates(
        self,
        tanimoto_threshold: float = 0.70,
        min_tracks: int = 2,
    ) -> List[Dict[str, Any]]:
        """Find molecules that appear in 2+ tracks above Tanimoto threshold.

        Parameters
        ----------
        tanimoto_threshold:
            Minimum Tanimoto similarity for two candidates to be considered
            the same molecule across tracks.
        min_tracks:
            Minimum number of tracks a molecule must appear in.

        Returns
        -------
        List of dicts with keys: smiles, tracks, max_tanimoto, candidates.
        """
        if not RDKIT_AVAILABLE:
            return []

        gen = rdFingerprintGenerator.GetMorganGenerator(
            radius=self.radius, fpSize=self.nbits
        )

        # Collect all candidates with their track labels
        all_candidates: List[Tuple[str, TrackCandidate]] = []
        for track, cands in self._track_candidates.items():
            for cand in cands:
                if cand.fingerprint is not None:
                    all_candidates.append((track, cand))

        if len(all_candidates) < 2:
            return []

        convergence: List[Dict[str, Any]] = []
        visited: set = set()

        for i, (track_i, cand_i) in enumerate(all_candidates):
            if i in visited:
                continue

            group_tracks = {track_i}
            group_candidates = [cand_i]
            group_indices = {i}

            fp_i = DataStructs.ExplicitBitVect(self.nbits)
            for bit_idx in np.where(cand_i.fingerprint)[0]:
                fp_i.SetBit(int(bit_idx))

            for j, (track_j, cand_j) in enumerate(all_candidates):
                if j <= i or j in visited or track_j == track_i:
                    continue
                if cand_j.fingerprint is None:
                    continue

                fp_j = DataStructs.ExplicitBitVect(self.nbits)
                for bit_idx in np.where(cand_j.fingerprint)[0]:
                    fp_j.SetBit(int(bit_idx))

                sim = DataStructs.TanimotoSimilarity(fp_i, fp_j)
                if sim >= tanimoto_threshold:
                    group_tracks.add(track_j)
                    group_candidates.append(cand_j)
                    group_indices.add(j)

            if len(group_tracks) >= min_tracks:
                visited.update(group_indices)
                convergence.append({
                    "smiles": cand_i.smiles,
                    "tracks": sorted(group_tracks),
                    "n_tracks": len(group_tracks),
                    "candidates": group_candidates,
                    "parent_smiles": cand_i.parent_smiles,
                })

        logger.info(
            "Convergence detection: %d candidates found across %d+ tracks",
            len(convergence), min_tracks,
        )
        return convergence

    def get_track_summary(self) -> Dict[str, Any]:
        """Return a summary of all track activity."""
        summary: Dict[str, Any] = {}
        for track, cands in self._track_candidates.items():
            novel = [c for c in cands if c.is_novel]
            summary[track] = {
                "total": len(cands),
                "novel": len(novel),
                "mean_tanimoto_to_approved": (
                    float(np.mean([c.tanimoto_to_approved for c in cands]))
                    if cands else 0.0
                ),
            }
        return summary

    # ------------------------------------------------------------------
    # Track-specific mutation strategies
    # ------------------------------------------------------------------

    def _hea_scaffold_modification(
        self,
        mol: Any,
        smiles: str,
        n: int,
        track: str,
    ) -> List[TrackCandidate]:
        """Track A: Hydroxyethylamine scaffold modifications."""
        return self._apply_substitutions(mol, smiles, n, track, "hea_modification", [
            # P1/P1' group modifications
            ("Cc1ccccc1", "Cc1cccc(F)c1"),
            ("Cc1ccccc1", "Cc1ccc(F)cc1"),
            ("Cc1ccccc1", "Cc1ccc(Cl)cc1"),
            ("Cc1ccccc1", "Cc1ccc(OC)cc1"),
            ("Cc1ccccc1", "Cc1ccc(CF)cc1"),
            # P2 group modifications
            ("c1ccc(N)cc1", "c1ccc(NS(=O)(=O)C)cc1"),
            ("c1ccc(N)cc1", "c1ccc(NC(=O)C)cc1"),
            ("c1ccc(N)cc1", "c1cc(F)c(N)cc1"),
        ])

    def _p2_group_modification(
        self,
        mol: Any,
        smiles: str,
        n: int,
        track: str,
    ) -> List[TrackCandidate]:
        """Track B: P2/P2' group modifications from PDB co-crystal structures."""
        return self._apply_substitutions(mol, smiles, n, track, "p2_modification", [
            # P2 isobutyl modifications
            ("CC(C)C", "CC(C)CF"),
            ("CC(C)C", "CC(C)CO"),
            ("CC(C)C", "CCC(C)C"),
            # Pyridine isosteres
            ("c1cccnc1", "c1ccncc1"),
            ("c1cccnc1", "c1ccc(F)nc1"),
            # Hydroxyl group modifications
            ("[C@@H](O)", "[C@@H](F)"),
        ])

    def _bis_thf_modification(
        self,
        mol: Any,
        smiles: str,
        n: int,
        track: str,
    ) -> List[TrackCandidate]:
        """Track C: Bis-THF and carbamate scaffold modifications."""
        return self._apply_substitutions(mol, smiles, n, track, "bis_thf_modification", [
            # Bis-THF ring modifications
            ("OC1COC2CCOC12", "OC1COC2CCOCC12"),
            ("OC1COC2CCOC12", "OC1COC2CCOC12"),
            # Carbamate modifications
            ("OC(=O)", "OC(=O)C"),
            ("NC(=O)O", "NC(=O)OC"),
            # Fluorine additions
            ("Cc1ccccc1", "Cc1ccc(F)cc1F"),
            ("Cc1ccccc1", "Cc1cc(F)ccc1"),
        ])

    def _guided_mutation(
        self,
        mol: Any,
        smiles: str,
        n: int,
        cognition_patterns: Dict[str, Any],
        track: str,
    ) -> List[TrackCandidate]:
        """Track D: Guided bit-flip mutation using CognitionStore patterns.

        Uses the per-bit statistics from the CognitionStore to preferentially
        flip bits that have historically improved binding affinity.
        """
        candidates: List[TrackCandidate] = []

        gen = rdFingerprintGenerator.GetMorganGenerator(
            radius=self.radius, fpSize=self.nbits
        )
        mol_fp = gen.GetFingerprint(mol)
        fp_array = np.array(mol_fp)

        # Extract high-value bits from cognition patterns
        high_value_bits = []
        for bit_str, stats in cognition_patterns.items():
            try:
                bit_idx = int(bit_str)
                avg_improvement = stats.get("avg_improvement", 0.0)
                if avg_improvement > 0:
                    high_value_bits.append((bit_idx, avg_improvement))
            except (ValueError, TypeError):
                continue

        # Sort by improvement value
        high_value_bits.sort(key=lambda x: x[1], reverse=True)
        top_bits = [b[0] for b in high_value_bits[:50]] if high_value_bits else []

        for i in range(n):
            new_fp = fp_array.copy()

            if top_bits and np.random.random() < 0.7:
                # Guided: flip high-value bits
                n_flips = np.random.randint(1, min(5, len(top_bits) + 1))
                bits_to_flip = np.random.choice(
                    top_bits, size=n_flips, replace=False
                )
                for bit in bits_to_flip:
                    new_fp[bit] = 1 - new_fp[bit]
                mod_type = "guided_bit_flip"
            else:
                # Exploration: random bit flips
                n_flips = np.random.randint(1, 8)
                bits_to_flip = np.random.choice(self.nbits, size=n_flips, replace=False)
                for bit in bits_to_flip:
                    new_fp[bit] = 1 - new_fp[bit]
                mod_type = "random_exploration"

            # Use parent SMILES as the candidate SMILES (fingerprint-only mode)
            # In production, a SMILES decoder would reconstruct from fingerprint
            # For now, apply SMARTS substitution to generate valid SMILES
            substituted = self._random_substitution(smiles)
            if substituted:
                candidates.append(TrackCandidate(
                    smiles=substituted,
                    track=track,
                    parent_smiles=smiles,
                    modification_type=mod_type,
                    metadata={"n_bits_flipped": int(n_flips)},
                ))

        return candidates

    def _apply_substitutions(
        self,
        mol: Any,
        smiles: str,
        n: int,
        track: str,
        mod_type: str,
        substitutions: List[Tuple[str, str]],
    ) -> List[TrackCandidate]:
        """Apply SMARTS-based substitutions to generate candidates."""
        candidates: List[TrackCandidate] = []
        rng = np.random.default_rng()

        for i in range(n):
            if not substitutions:
                break
            # Pick a random substitution
            from_smarts, to_smarts = substitutions[i % len(substitutions)]
            new_smiles = smiles.replace(from_smarts, to_smarts, 1)

            # Validate with RDKit
            new_mol = Chem.MolFromSmiles(new_smiles)
            if new_mol is None:
                # Fallback: random atom substitution
                new_smiles = self._random_substitution(smiles)
                if new_smiles is None:
                    continue

            candidates.append(TrackCandidate(
                smiles=new_smiles,
                track=track,
                parent_smiles=smiles,
                modification_type=mod_type,
            ))

        return candidates

    def _random_modification(
        self,
        mol: Any,
        smiles: str,
        n: int,
        track: str,
    ) -> List[TrackCandidate]:
        """Fallback random modification strategy — delegates to _apply_substitutions
        with a broad substitution table.
        """
        substitutions = [
            ("F", "Cl"), ("Cl", "F"), ("OC", "FC"), ("N", "NC"),
            ("c1ccccc1", "c1ccncc1"), ("C(C)C", "C(C)CF"),
            ("OC", "OCC"), ("NC", "NCC"),
        ]
        return self._apply_substitutions(mol, smiles, n, track, "random_modification", substitutions)

    def _random_substitution(self, smiles: str) -> Optional[str]:
        """Apply a random valid substitution to a SMILES string."""
        substitutions = [
            ("F", "Cl"), ("Cl", "F"), ("OC", "FC"), ("N", "NC"),
            ("c1ccccc1", "c1ccncc1"), ("C(C)C", "C(C)CF"),
            ("OC", "OCC"), ("NC", "NCC"),
        ]
        for from_s, to_s in np.random.permutation(substitutions):
            if from_s in smiles:
                new_smiles = smiles.replace(from_s, to_s, 1)
                mol = Chem.MolFromSmiles(new_smiles)
                if mol:
                    return Chem.MolToSmiles(mol)
        return smiles  # Return original if no valid substitution found

    def _max_tanimoto_to_approved(self, fp: Any) -> float:
        """Compute maximum Tanimoto similarity to any approved HIV PI."""
        if not self._approved_fps:
            return 0.0
        sims = DataStructs.BulkTanimotoSimilarity(fp, self._approved_fps)
        return float(max(sims)) if sims else 0.0
