#!/usr/bin/env python3
"""
backfill_citation_verdicts.py
─────────────────────────────
Backfills null citationVerdict values for all candidates in the discovery DB.

Usage:
    python scripts/backfill_citation_verdicts.py \
        --db /data/discovery.db \
        --citation-api https://citation.manus.space/api/public/verify-claim \
        --batch-size 10 \
        --dry-run

The script:
1. Reads all candidates with citationVerdict IS NULL from the SQLite DB
2. Generates a natural-language claim for each candidate (SMILES + pIC50)
3. Submits claims to the citation.manus.space batch-verify endpoint
4. Updates the citationVerdict column in the DB

Safe to run multiple times (idempotent — only processes NULL rows).
"""
from __future__ import annotations
import argparse
import json
import logging
import sqlite3
import time
from pathlib import Path
from typing import Optional
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

CITATION_API = "https://citation.manus.space/api/public/batch-verify"
VERTICAL = "hiv_protease"
BATCH_SIZE = 10
RATE_LIMIT_DELAY = 1.0  # seconds between batches


def build_claim(smiles: str, pic50: Optional[float], cycle_id: int) -> str:
    """Generate a verifiable natural-language claim for a candidate."""
    if pic50 and pic50 > 0:
        ic50_nm = 10 ** (9 - pic50)
        return (
            f"This HIV-1 protease inhibitor (cycle {cycle_id}) has a predicted binding "
            f"affinity of pIC50 {pic50:.3f} ({ic50_nm:.1f} nM), consistent with "
            f"hydroxyethylamine isostere scaffolds reported in PubMed literature."
        )
    return (
        f"This HIV-1 protease inhibitor candidate (cycle {cycle_id}) was generated by "
        f"structure-based drug design targeting the HIV-1 protease active site."
    )


def verify_batch(claims: list[str], api_url: str) -> list[dict]:
    """Submit a batch of claims to the citation API."""
    try:
        resp = requests.post(
            api_url,
            json={"claims": claims, "vertical": VERTICAL},
            timeout=60,
        )
        resp.raise_for_status()
        data = resp.json()
        return data.get("results", [])
    except Exception as e:
        log.error("Batch verify failed: %s", e)
        return [{"verdict": "error", "confidence": 0, "error": str(e)} for _ in claims]


def run_backfill(
    db_path: str,
    api_url: str = CITATION_API,
    batch_size: int = BATCH_SIZE,
    dry_run: bool = False,
) -> dict:
    """Main backfill loop."""
    db = sqlite3.connect(db_path)
    db.row_factory = sqlite3.Row

    # Find all candidates with null citationVerdict
    # Try both table names used across engine versions
    table = None
    for t in ("evolution_cycles", "candidates", "cognition_store"):
        try:
            db.execute(f"SELECT 1 FROM {t} LIMIT 1")
            table = t
            break
        except sqlite3.OperationalError:
            continue

    if not table:
        log.error("No candidates table found in DB")
        return {"error": "no_table"}

    rows = db.execute(
        f"SELECT id, smiles, predicted_affinity, cycle_id FROM {table} "
        f"WHERE citation_verdict IS NULL ORDER BY id"
    ).fetchall()

    log.info("Found %d candidates with null citationVerdict in table '%s'", len(rows), table)

    if dry_run:
        log.info("[DRY RUN] Would process %d candidates", len(rows))
        return {"dry_run": True, "count": len(rows)}

    updated = 0
    errors = 0

    for i in range(0, len(rows), batch_size):
        batch = rows[i : i + batch_size]
        claims = [
            build_claim(
                r["smiles"] or "",
                r["predicted_affinity"],
                r["cycle_id"] or i + j,
            )
            for j, r in enumerate(batch)
        ]

        results = verify_batch(claims, api_url)

        for j, (row, result) in enumerate(zip(batch, results)):
            verdict = result.get("verdict", "Insufficient Evidence")
            confidence = result.get("confidence", 0.0)
            pmids = json.dumps(result.get("citedPmids", []))

            db.execute(
                f"UPDATE {table} SET citation_verdict=?, citation_confidence=?, "
                f"citation_pmids=? WHERE id=?",
                (verdict, confidence, pmids, row["id"]),
            )
            updated += 1
            log.info(
                "  [%d/%d] id=%s verdict=%s confidence=%.2f",
                i + j + 1,
                len(rows),
                row["id"],
                verdict,
                confidence,
            )

        db.commit()
        log.info("Batch %d/%d committed (%d updated so far)", i // batch_size + 1, -(-len(rows) // batch_size), updated)

        if i + batch_size < len(rows):
            time.sleep(RATE_LIMIT_DELAY)

    db.close()
    log.info("Backfill complete: %d updated, %d errors", updated, errors)
    return {"updated": updated, "errors": errors}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Backfill null citationVerdicts")
    parser.add_argument("--db", required=True, help="Path to SQLite discovery DB")
    parser.add_argument("--citation-api", default=CITATION_API, help="Batch verify API URL")
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    parser.add_argument("--dry-run", action="store_true", help="Count rows without updating")
    args = parser.parse_args()

    result = run_backfill(
        db_path=args.db,
        api_url=args.citation_api,
        batch_size=args.batch_size,
        dry_run=args.dry_run,
    )
    print(json.dumps(result, indent=2))
